/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomSlugRouteImport } from './routes/room.$slug'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSlugRoute = RoomSlugRouteImport.update({
  id: '/room/$slug',
  path: '/room/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/playlists': typeof PlaylistsRoute
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRoute
  '/shop': typeof ShopRoute
  '/profile/$id': typeof ProfileIdRoute
  '/room/$slug': typeof RoomSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/playlists': typeof PlaylistsRoute
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRoute
  '/shop': typeof ShopRoute
  '/profile/$id': typeof ProfileIdRoute
  '/room/$slug': typeof RoomSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/playlists': typeof PlaylistsRoute
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRoute
  '/shop': typeof ShopRoute
  '/profile/$id': typeof ProfileIdRoute
  '/room/$slug': typeof RoomSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/friends'
    | '/login'
    | '/playlists'
    | '/register'
    | '/rooms'
    | '/shop'
    | '/profile/$id'
    | '/room/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/friends'
    | '/login'
    | '/playlists'
    | '/register'
    | '/rooms'
    | '/shop'
    | '/profile/$id'
    | '/room/$slug'
  id:
    | '__root__'
    | '/'
    | '/friends'
    | '/login'
    | '/playlists'
    | '/register'
    | '/rooms'
    | '/shop'
    | '/profile/$id'
    | '/room/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRoute: typeof FriendsRoute
  LoginRoute: typeof LoginRoute
  PlaylistsRoute: typeof PlaylistsRoute
  RegisterRoute: typeof RegisterRoute
  RoomsRoute: typeof RoomsRoute
  ShopRoute: typeof ShopRoute
  ProfileIdRoute: typeof ProfileIdRoute
  RoomSlugRoute: typeof RoomSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$slug': {
      id: '/room/$slug'
      path: '/room/$slug'
      fullPath: '/room/$slug'
      preLoaderRoute: typeof RoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRoute: FriendsRoute,
  LoginRoute: LoginRoute,
  PlaylistsRoute: PlaylistsRoute,
  RegisterRoute: RegisterRoute,
  RoomsRoute: RoomsRoute,
  ShopRoute: ShopRoute,
  ProfileIdRoute: ProfileIdRoute,
  RoomSlugRoute: RoomSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
